// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TE.TT.MarketApi.Database;

#nullable disable

namespace TE.TT.MarketApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250703185453_Rename_Alpace")]
    partial class Rename_Alpace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Exchange")
                        .HasColumnType("longtext");

                    b.Property<string>("Kind")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.Property<double?>("TickSize")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdateData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Gics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("IndustryGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("SubIndustryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Gics");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("DefualtOrderSize")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Exchange")
                        .HasColumnType("longtext");

                    b.Property<int?>("MaxOrderSize")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TradingHoursId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TradingHoursId");

                    b.ToTable("MappingBase");

                    b.HasDiscriminator().HasValue("MappingBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.TradingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ElectronicEnd")
                        .HasColumnType("longtext");

                    b.Property<string>("ElectronicStart")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("MappingId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RegularEnd")
                        .HasColumnType("longtext");

                    b.Property<string>("RegularStart")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MappingId")
                        .IsUnique();

                    b.ToTable("TradingHours");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingAplaca", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingAplaca");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingDxfeed", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingDxfeed");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingOanda", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingOanda");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingSimulation", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingSimulation");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Gics", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.Profile", "Profile")
                        .WithOne("Gics")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.Gics", "ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingBase", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.TradingHours", "TradingHours")
                        .WithMany()
                        .HasForeignKey("TradingHoursId");

                    b.Navigation("TradingHours");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Profile", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Profile")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.Profile", "AssetId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.TradingHours", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.MappingBase", "Mapping")
                        .WithOne()
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.TradingHours", "MappingId");

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingAplaca", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Alpaca")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingAplaca", "AssetId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingDxfeed", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Dxfeed")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingDxfeed", "AssetId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingOanda", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Oanda")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingOanda", "AssetId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingSimulation", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Simulation")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingSimulation", "AssetId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.AssetEntity", b =>
                {
                    b.Navigation("Alpaca");

                    b.Navigation("Dxfeed");

                    b.Navigation("Oanda");

                    b.Navigation("Profile");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Profile", b =>
                {
                    b.Navigation("Gics");
                });
#pragma warning restore 612, 618
        }
    }
}
