// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TE.TT.MarketApi.Database;

#nullable disable

namespace TE.TT.MarketApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250703092801_edit")]
    partial class edit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Gics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("IndustryGroupId")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("SubIndustryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Gics");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DefualtOrderSize")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxOrderSize")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TradingHoursId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TradingHoursId");

                    b.ToTable("MappingBase");

                    b.HasDiscriminator().HasValue("MappingBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.TradingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ElectronicEnd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ElectronicStart")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RegularEnd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegularStart")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MappingId")
                        .IsUnique();

                    b.ToTable("TradingHours");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingAplace", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingAplace");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingDxfeed", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingDxfeed");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingOanda", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingOanda");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingSimulation", b =>
                {
                    b.HasBaseType("TE.TT.MarketApi.Database.Entity.MappingBase");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MappingSimulation");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Gics", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.Profile", "Profile")
                        .WithOne("Gics")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.Gics", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingBase", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.TradingHours", "TradingHours")
                        .WithMany()
                        .HasForeignKey("TradingHoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradingHours");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Profile", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Profile")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.Profile", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.TradingHours", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.MappingBase", "Mapping")
                        .WithOne()
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.TradingHours", "MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingAplace", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Aplace")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingAplace", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingDxfeed", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Dxfeed")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingDxfeed", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingOanda", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Oanda")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingOanda", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.MappingSimulation", b =>
                {
                    b.HasOne("TE.TT.MarketApi.Database.Entity.AssetEntity", "Asset")
                        .WithOne("Simulation")
                        .HasForeignKey("TE.TT.MarketApi.Database.Entity.MappingSimulation", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.AssetEntity", b =>
                {
                    b.Navigation("Aplace")
                        .IsRequired();

                    b.Navigation("Dxfeed")
                        .IsRequired();

                    b.Navigation("Oanda")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Simulation")
                        .IsRequired();
                });

            modelBuilder.Entity("TE.TT.MarketApi.Database.Entity.Profile", b =>
                {
                    b.Navigation("Gics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
